Versión inicial para iniciar el desarrollo del proyecto SchoolBook
school-book/schoolbook-app pull request #1
Opened 2020-07-26 04:43 UTC by jorgerdc

Se define el caso de estudio. Esta es una. primera versión la cual se irá refinando conforme se avance en el diseño.
La idea es generar un caso de estudio sencillo de entender para poder ser implementado empleando principios básicos de la arquitectura de microservicios.

2020-07-31 04:38 UTC, alexJava2015 requested changes

2020-07-31 04:38 UTC, alexJava2015 commented on README.md
> +* Revisar la carpeta docs en la que se encuentran los siguientes documentos:
Corregir la descripción de este punto, ya que se mencionan archivos que aun no existen.

2020-07-31 04:38 UTC, alexJava2015 commented on README.md
> +	* [schoolbook](https://github.com/jorgerdc/schoolbook) (este repositorio)  Contiene la definición del proyecto, documentación, así como el código de la aplicación web.
Cambiar la ruta por una valida, ya que esta no existe.

2020-07-31 04:38 UTC, alexJava2015 commented on docs/caso-estudio.md
> +* Para cada ejemplar se registra el número de ejemplar iniciando en 0001 y la ubicación dentro de la biblioteca.
Mejorar la redacción para no repetir la palabra ejemplar.

2020-07-31 04:38 UTC, alexJava2015 commented on docs/caso-estudio.md
> +|Status            |Descripción
Pasar a español la palabra "status".

2020-07-31 04:38 UTC, alexJava2015 commented on docs/caso-estudio.md
> +|EN LINEA          | EL libro digital está disponible para ser accedido vía internet
Corregir la letra "L" pasarla a minúscula dentro del texto "EL libro ...."

2020-07-31 04:38 UTC, alexJava2015 commented on docs/caso-estudio.md
> +* Se requiere llevar el control de un histórico de estos status.
Pasar a español la palabra "status" y que todo el texto  del documento esta así.

2020-07-31 04:38 UTC, alexJava2015 commented on docs/caso-estudio.md
> +Status  |Descripción
Pasar a español la palabra "status" y que todo el texto del documento esta así.

2020-07-31 04:38 UTC, alexJava2015 commented on docs/caso-estudio.md
> +* Las bibliotecas pueden solicitar a SchooBook el surtido ya sea de libros existentes o de nuevos libros.  Para ello se requiere registrar una solicitud de surtido.   Se almacena un folio de solicitu
Corregir la palabra "SchooBook", falta letra "l" en la palabra "School"

2020-07-31 04:38 UTC, alexJava2015 commented on docs/caso-estudio.md
> +Status | Descripción
Pasar a español la palabra "status" y que todo el texto del documento esta así.

2020-07-31 17:22 UTC, rhofp commented on docs/caso-estudio.md
> +* Con base a estos datos, en el contrato se especifica la cuota mensual que la escuela deberá pagar.   Una  vez que el contrato es firmado, se obtiene una copia en formato PDF el cual se almacena en
Debería decir: "Con base en estos datos" ...

2020-07-31 17:35 UTC, rhofp commented on docs/caso-estudio.md
> +* Los prestamos aplican a ambos tipos de libros (ejemplares y digitales).
Acento en "prestamos" tanto en el título como al inicio del primer párrafo

2020-07-31 17:41 UTC, rhofp commented on docs/caso-estudio.md
> +VIGENTE     | El préstamo se ha otorgado y las fechas de entrega de cada uno de sus ejemplares aun no expiran.
"aun" debería llevar tilde no?

2020-07-31 17:43 UTC, rhofp commented on docs/caso-estudio.md
> +CON MULTA   | El Usuario aun no ha realizado la entrega del préstamo, tiene al menos un ejemplar con fecha de entrega expirada y han pasado los 2 días que el sistema otorga para regresar los ejemplar
La "U" mayúscula de Usuario es intencional la identificar la actor "usuario"? Si no se sugiere cambiarla a minúscula

2020-07-31 17:44 UTC, rhofp commented on docs/caso-estudio.md
> +CON MULTA   | El Usuario aun no ha realizado la entrega del préstamo, tiene al menos un ejemplar con fecha de entrega expirada y han pasado los 2 días que el sistema otorga para regresar los ejemplar
Colocar la tilde de "aun"

2020-07-31 17:58 UTC, rhofp commented on docs/caso-estudio.md
> +* Para usuarios que no pertenecen a las escuelas, estos no podrán acceder a los prestamos  que son ofrecidos por las escuelas.
acento en "prestamos"

2020-08-02 00:02 UTC, jorgerdc commented on README.md
> +* Revisar la carpeta docs en la que se encuentran los siguientes documentos:
ok, se esta trabajando en ello.

2020-08-02 00:08 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Para cada ejemplar se registra el número de ejemplar iniciando en 0001 y la ubicación dentro de la biblioteca.
Se modifica la redacción.

2020-08-02 00:09 UTC, jorgerdc commented on docs/caso-estudio.md
> +|Status            |Descripción
Considero que debería quedarse así. La traducción en español sería "Estado" la cual es un tanto ambigua, por ejemplo, se puede confundir con "Estados de la república", etc.
En documentos formales ya se vale que existan palabras en inglés cuando su traducción provoque confusión

2020-08-02 00:10 UTC, jorgerdc commented on docs/caso-estudio.md
> +|EN LINEA          | EL libro digital está disponible para ser accedido vía internet
Corregido

2020-08-02 00:10 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Se requiere llevar el control de un histórico de estos status.
Mismo comentario respecto al caso anterior.

2020-08-02 00:10 UTC, jorgerdc commented on docs/caso-estudio.md
> +Status  |Descripción
Mismo comentario respecto al caso anterior.

2020-08-02 00:11 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Las bibliotecas pueden solicitar a SchooBook el surtido ya sea de libros existentes o de nuevos libros.  Para ello se requiere registrar una solicitud de surtido.   Se almacena un folio de solicitu
corregido

2020-08-02 00:11 UTC, jorgerdc commented on docs/caso-estudio.md
> +Status | Descripción
Mismo comentario que el caso anterior.

2020-08-02 00:11 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Con base a estos datos, en el contrato se especifica la cuota mensual que la escuela deberá pagar.   Una  vez que el contrato es firmado, se obtiene una copia en formato PDF el cual se almacena en
corregido

2020-08-02 00:12 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Los prestamos aplican a ambos tipos de libros (ejemplares y digitales).
corregido

2020-08-02 00:13 UTC, jorgerdc commented on docs/caso-estudio.md
> +VIGENTE     | El préstamo se ha otorgado y las fechas de entrega de cada uno de sus ejemplares aun no expiran.
corregido

2020-08-02 00:14 UTC, jorgerdc commented on docs/caso-estudio.md
> +CON MULTA   | El Usuario aun no ha realizado la entrega del préstamo, tiene al menos un ejemplar con fecha de entrega expirada y han pasado los 2 días que el sistema otorga para regresar los ejemplar
corregido.

2020-08-02 00:14 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Para usuarios que no pertenecen a las escuelas, estos no podrán acceder a los prestamos  que son ofrecidos por las escuelas.
corregido

2020-08-02 03:57 UTC, alexJava2015 commented on README.md
> +* Revisar la carpeta docs en la que se encuentran los siguientes documentos:
Perfecto se cierra comentario.

2020-08-02 03:59 UTC, alexJava2015 commented on docs/caso-estudio.md
> +* Para cada ejemplar se registra el número de ejemplar iniciando en 0001 y la ubicación dentro de la biblioteca.
Perfecto se cierra comentario.

2020-08-02 04:08 UTC, alexJava2015 commented on docs/caso-estudio.md
> +|Status            |Descripción
De acuerdo, con esta aclaración, queda en inglés la palabra. se cierra comentario.

2020-08-02 04:08 UTC, alexJava2015 commented on docs/caso-estudio.md
> +|EN LINEA          | EL libro digital está disponible para ser accedido vía internet
Se cierra comentario.

2020-08-02 04:12 UTC, alexJava2015 commented on docs/caso-estudio.md
> +* Se requiere llevar el control de un histórico de estos status.
De acuerdo, con la aclaración, queda en inglés la palabra. se cierra comentario.

2020-08-02 04:12 UTC, alexJava2015 commented on docs/caso-estudio.md
> +Status  |Descripción
De acuerdo, con la aclaración, queda en inglés la palabra. se cierra comentario.

2020-08-02 04:12 UTC, alexJava2015 commented on docs/caso-estudio.md
> +* Las bibliotecas pueden solicitar a SchooBook el surtido ya sea de libros existentes o de nuevos libros.  Para ello se requiere registrar una solicitud de surtido.   Se almacena un folio de solicitu
Perfecto se cierra comentario.

2020-08-02 04:13 UTC, alexJava2015 commented on docs/caso-estudio.md
> +Status | Descripción
De acuerdo, con la aclaración, queda en inglés la palabra. se cierra comentario.

2020-08-02 19:15 UTC, alexJava2015 approved these changes

2020-08-02 19:42 UTC, jorgerdc commented on README.md
> +	* [schoolbook](https://github.com/jorgerdc/schoolbook) (este repositorio)  Contiene la definición del proyecto, documentación, así como el código de la aplicación web.
Resuelto.

2020-08-06 02:00 UTC, jorgerdc commented
@rhofp please, podrías echarle un ojo rápido al segundo update?  Este merge es importante para el curso.

2020-08-06 02:54 UTC, rhofp commented on docs/caso-estudio.md
> +* Para realizar los pagos mensuales, la escuela puede proporcionar varios números de tarjeta de crédito, puede ser inclusive a nivel de biblioteca. Se registra el número de tarjeta, su tipo, mes y añ
Cuando dices que "puede ser a nivel de biblioteca" se refiere a que es posible registrar una tarjeta por biblioteca, cierto? Por que me parece que se puede malinterpretar como que la entidad biblioteca puede registrar "n" tarjetas de crédito, lo cual creo que es falso.

2020-08-06 03:08 UTC, rodrigofrancisco requested changes
Listo @jorgerdc

2020-08-06 03:08 UTC, rhofp commented on docs/caso-estudio.md
> +* Algunos libros digitales incluyen material multimedia, archivos de audio y/o archivos de vídeo.  Para cada archivo se registra un número de archivo,  su tipo (vídeo, audio, etc.), su formato y una
Ok, entonces tipo describe si es vídeo, audio, etc. y el formato describe si es jpg, mp3, etc. cierto? 
Creo que sería buena idea específicarlo por si algún despistado como yo se confunde en eso. Porque en el commit anterior había entendido que el tipo era jpg, png,...

2020-08-06 17:45 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Para realizar los pagos mensuales, la escuela puede proporcionar varios números de tarjeta de crédito, puede ser inclusive a nivel de biblioteca. Se registra el número de tarjeta, su tipo, mes y añ
Es correcto.  Una escuela puede registrar varias tarjetas, pero  para cada biblioteca solo se asigna una. Modificaré redacción para aclarar este punto  👍

2020-08-06 17:52 UTC, jorgerdc commented on docs/caso-estudio.md
> +* Algunos libros digitales incluyen material multimedia, archivos de audio y/o archivos de vídeo.  Para cada archivo se registra un número de archivo,  su tipo (vídeo, audio, etc.), su formato y una
ok de acuerdo.

2020-08-06 19:34 UTC, rodrigofrancisco approved these changes

2020-08-06 20:50 UTC, alexJava2015 requested changes

2020-08-06 20:50 UTC, alexJava2015 commented on README.md
> +* El código fuente del proyecto se distribuye en diversos repositorios los cuales se pueden consultar [en este enlace.]([https://github.com/school-book/](https://github.com/school-book/))
No se muestra ningún enlace, favor de corregir.

2020-08-06 23:23 UTC, merged